// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE60zN1bLvqGFOMKJs1LmpvpSvGpYaXRE',
    appId: '1:506873159632:android:5dbe7040e5b2e251fee3d5',
    messagingSenderId: '506873159632',
    projectId: 'appbanhang-d8faf',
    storageBucket: 'appbanhang-d8faf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXvNU1dj385qA42OsUNINtD233d5qzDZE',
    appId: '1:506873159632:ios:bff66296f0dc05effee3d5',
    messagingSenderId: '506873159632',
    projectId: 'appbanhang-d8faf',
    storageBucket: 'appbanhang-d8faf.firebasestorage.app',
    androidClientId: '506873159632-8aad0koaap2skg0t2v1loulpc1d7ka69.apps.googleusercontent.com',
    iosClientId: '506873159632-ieehjsf8vughq67mug3akc5o2jmf41jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryManagerApp',
  );
}
